version: '3'

services:

  user_db:
    image: postgres:latest
    container_name: user_postgres_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mydemy

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: pgadmin
    networks:
      - mydemy
  
  user_service:
    container_name: user_service
    image: user_service  # Assuming this image is built correctly
    build:
      context: ./user
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - ./user:/usr/src/app
    ports:
      - "8081:8081"
    depends_on:
      - user_db
    restart: unless-stopped
    networks:
      - mydemy

networks:
  mydemy:
    driver: bridge

volumes:
  user_postgres_data:  # Define this volume if not already defined elsewhere

# version: '3'

# services:

#   user_db:
#     image: postgres:latest
#     container_name: user_postgres_db
#     environment:
#       POSTGRES_DB: user_db
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - user_postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped
#     networks:
#       - mydemy
  
#   user_service:
#     container_name: user_service
#     image: user_service
#     build:
#       context: ./user
#       dockerfile: ./Dockerfile
#     command: python manage.py runserver 0.0.0.0:8081
#     volumes:
#       - ./user:/usr/src/app
#     ports:
#       - "8081:8081"
#     links:
#       - user_db
#     depends_on:
#       - user_db
#     restart: unless-stopped
#     networks:
#       - mydemy

  
# networks:
#   mydemy:
#     driver: bridge
# volumes:
#   user_postgres_data:

